<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="auv_robot">

  <!-- 机器人尺寸参数 -->
  <xacro:property name="PI" value="3.14159265359"/>
  <xacro:property name="hull_length" value="2.0"/>
  <xacro:property name="hull_radius" value="0.15"/>
  <xacro:property name="hull_mass" value="25.0"/>
  
  <!-- 材料定义 -->
  <material name="hull_orange">
    <color rgba="1.0 0.6 0.0 1.0"/>
  </material>
  
  <material name="sensor_black">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>

  <!-- 主船体 -->
  <link name="base_link">
    <inertial>
      <mass value="${hull_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="2.0" ixy="0.0" ixz="0.0"
               iyy="8.0" iyz="0.0"
               izz="8.0"/>
    </inertial>
    
    <visual name="hull_visual">
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${hull_radius}" length="${hull_length}"/>
      </geometry>
      <material name="hull_orange"/>
    </visual>
    
    <collision name="hull_collision">
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${hull_radius}" length="${hull_length}"/>
      </geometry>
    </collision>
  </link>

  <!-- 相机 -->
  <link name="camera_link">
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.12 0.08"/>
      </geometry>
      <material name="sensor_black"/>
    </visual>
  </link>

  <joint name="hull_to_camera" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="1.2 0 0" rpy="0 0 0"/>
  </joint>

  <!-- 其他传感器连接 -->
  <link name="imu_link">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="sensor_black"/>
    </visual>
  </link>

  <joint name="hull_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- 简化的其他传感器 -->
  <link name="sonar_link">
    <inertial>
      <mass value="0.8"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="0.06" length="0.15"/>
      </geometry>
      <material name="sensor_black"/>
    </visual>
  </link>

  <joint name="hull_to_sonar" type="fixed">
    <parent link="base_link"/>
    <child link="sonar_link"/>
    <origin xyz="0.4 0 -0.08" rpy="0 0 0"/>
  </joint>

  <link name="dvl_link">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.12 0.12 0.06"/>
      </geometry>
      <material name="sensor_black"/>
    </visual>
  </link>

  <joint name="hull_to_dvl" type="fixed">
    <parent link="base_link"/>
    <child link="dvl_link"/>
    <origin xyz="0.3 0 -0.2" rpy="0 0 0"/>
  </joint>

  <link name="gps_link">
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.08"/>
      </geometry>
      <material name="sensor_black"/>
    </visual>
  </link>

  <joint name="hull_to_gps" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="0 0 0.2" rpy="0 0 0"/>
  </joint>

  <!-- 控制鳍 -->
  <link name="dorsal_fin">
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.02" ixy="0.0" ixz="0.0"
               iyy="0.02" iyz="0.0"
               izz="0.02"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.03 0.3"/>
      </geometry>
      <material name="hull_orange"/>
    </visual>
  </link>

  <joint name="hull_to_dorsal_fin" type="fixed">
    <parent link="base_link"/>
    <child link="dorsal_fin"/>
    <origin xyz="-0.8 0 0.15" rpy="0 0 0"/>
  </joint>

  <link name="left_fin">
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.02 0.2"/>
      </geometry>
      <material name="hull_orange"/>
    </visual>
  </link>

  <joint name="hull_to_left_fin" type="fixed">
    <parent link="base_link"/>
    <child link="left_fin"/>
    <origin xyz="-0.7 0.15 0" rpy="0 0 0"/>
  </joint>

  <link name="right_fin">
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.02 0.2"/>
      </geometry>
      <material name="hull_orange"/>
    </visual>
  </link>

  <joint name="hull_to_right_fin" type="fixed">
    <parent link="base_link"/>
    <child link="right_fin"/>
    <origin xyz="-0.7 -0.15 0" rpy="0 0 0"/>
  </joint>

  <link name="main_thruster">
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.05" ixy="0.0" ixz="0.0"
               iyy="0.05" iyz="0.0"
               izz="0.05"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="0.08" length="0.25"/>
      </geometry>
      <material name="sensor_black"/>
    </visual>
  </link>

  <joint name="hull_to_main_thruster" type="fixed">
    <parent link="base_link"/>
    <child link="main_thruster"/>
    <origin xyz="-1.0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="nose_cone">
    <inertial>
      <mass value="1.5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0"
               izz="0.1"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${hull_radius * 0.9}"/>
      </geometry>
      <material name="sensor_black"/>
    </visual>
  </link>

  <joint name="hull_to_nose" type="fixed">
    <parent link="base_link"/>
    <child link="nose_cone"/>
    <origin xyz="0.9 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo 材质配置 -->
  <gazebo reference="base_link">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="camera_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="nose_cone">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="dorsal_fin">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="left_fin">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="right_fin">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="main_thruster">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- 🔧 修复：恢复正确的planar_move插件配置 -->
  <gazebo>
    <plugin name="planar_move_controller" filename="libgazebo_ros_planar_move.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <publish_rate>50.0</publish_rate>
      <publish_odom>true</publish_odom>
      <publish_tf>true</publish_tf>
      
      <!-- 🔧 关键：确保3D运动支持 -->
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_z>0.0001</covariance_z>
      <covariance_yaw>0.01</covariance_yaw>
    </plugin>
  </gazebo>

  <!-- 相机传感器 -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="forward_camera">
      <update_rate>10.0</update_rate>
      <camera name="forward_camera">
        <horizontal_fov>1.396</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>50</far>
        </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/</namespace>
          <argument>--ros-args --remap image_raw:=/forward_camera/image_raw</argument>
          <argument>--ros-args --remap camera_info:=/forward_camera/camera_info</argument>
        </ros>
        <camera_name>forward_camera</camera_name>
        <frame_name>camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- IMU 传感器 -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <ros>
          <namespace>/</namespace>
          <argument>--ros-args --remap ~/out:=/imu/data</argument>
        </ros>
        <frame_name>imu_link</frame_name>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
    </sensor>
  </gazebo>

</robot>