# Dolphin SLAM - 仿真航点配置
# 定义机器人在仿真中要访问的航点

# 航点格式: [x, y, z, yaw]
# x, y, z: 位置坐标（米）
# yaw: 偏航角（弧度）

waypoint_missions:
  # 默认任务 - 浅水探索
  default:
    name: "Shallow Water Exploration"
    waypoints:
      - position: [0.0, 0.0, -3.0]
        orientation: 0.0
        hold_time: 2.0
        
      - position: [10.0, 0.0, -4.0]
        orientation: 0.0
        hold_time: 1.0
        
      - position: [10.0, 10.0, -5.0]
        orientation: 1.5708  # 90度
        hold_time: 1.0
        
      - position: [0.0, 10.0, -4.0]
        orientation: 3.1416  # 180度
        hold_time: 1.0
        
      - position: [0.0, 0.0, -3.0]
        orientation: 0.0
        hold_time: 2.0
        
    # 航点间的行为
    transit_speed: 0.5      # m/s
    transit_mode: "direct"  # direct, spline, dubins
    depth_first: false      # 是否先调整深度
    
  # 温和深度变化任务
  depth_profile:
    name: "Gentle Depth Profile Mission"
    waypoints:
      - position: [0.0, 0.0, -2.0]
        orientation: 0.0
        hold_time: 3.0
        
      - position: [5.0, 0.0, -4.0]
        orientation: 0.0
        hold_time: 2.0
        
      - position: [10.0, 0.0, -6.0]
        orientation: 0.0
        hold_time: 2.0
        
      - position: [15.0, 0.0, -8.0]
        orientation: 0.0
        hold_time: 2.0
        
      - position: [20.0, 0.0, -6.0]
        orientation: 0.0
        hold_time: 2.0
        
      - position: [25.0, 0.0, -4.0]
        orientation: 0.0
        hold_time: 2.0
        
    transit_speed: 0.3
    transit_mode: "spline"
    maintain_altitude: false
    
  # 温和螺旋探索
  spiral_exploration:
    name: "Gentle Spiral Exploration"
    type: "parametric"  # 参数化路径
    parameters:
      center: [0.0, 0.0]
      start_depth: -2.0
      end_depth: -8.0
      radius: 5.0
      turns: 3.0
      direction: "clockwise"
      
    speed_profile:
      type: "constant"
      value: 0.4  # m/s
      
  # 浅水搜索网格
  search_grid:
    name: "Shallow Water Search"
    type: "lawnmower"
    parameters:
      origin: [0.0, 0.0, -4.0]
      length: 30.0    # 米
      width: 20.0     # 米
      spacing: 3.0    # 航线间距
      orientation: 0.0  # 网格方向
      
    transit_speed: 0.6
    turn_radius: 2.0
    overlap: 0.5  # 米
    
  # 浅水墙体跟踪
  wall_following:
    name: "Shallow Wall Following"
    waypoints:
      - position: [0.0, 5.0, -4.0]
        orientation: 0.0
        wall_distance: 2.0
        
      - position: [20.0, 5.0, -5.0]
        orientation: 0.0
        wall_distance: 2.0
        
    mode: "right_wall"  # left_wall, right_wall
    sensor: "sonar"
    maintain_distance: 2.0  # 米
    speed: 0.3
    
  # 浅水特征探索
  feature_rich_exploration:
    name: "Shallow Feature Exploration"
    waypoints:
      # 保持在浅水区域
      - position: [5.0, 5.0, -3.0]
        orientation: 0.785  # 45度
        hold_time: 5.0
        notes: "浅水珊瑚区域"
        
      - position: [8.0, 12.0, -4.0]
        orientation: 1.57
        hold_time: 5.0
        notes: "浅水岩石区域"
        
      - position: [15.0, 15.0, -5.0]
        orientation: 2.36
        hold_time: 5.0
        notes: "浅水探索点"
        
      - position: [12.0, 8.0, -4.0]
        orientation: 3.14
        hold_time: 3.0
        notes: "返回路径"
        
    transit_speed: 0.3
    imaging_mode: true  # 降低速度以获得更好的图像
    sonar_active: true
    
  # 浅水闭环测试路径
  loop_closure_test:
    name: "Shallow Loop Closure Test"
    waypoints:
      # 创建一个有意的闭环，保持在浅水
      - position: [0.0, 0.0, -3.0]
        orientation: 0.0
        marker: "start"
        
      - position: [10.0, 0.0, -4.0]
        orientation: 0.0
        
      - position: [15.0, 5.0, -5.0]
        orientation: 0.785
        
      - position: [15.0, 15.0, -6.0]
        orientation: 1.57
        
      - position: [10.0, 20.0, -5.0]
        orientation: 2.36
        
      - position: [0.0, 20.0, -4.0]
        orientation: 3.14
        
      - position: [-5.0, 15.0, -3.0]
        orientation: 3.93
        
      - position: [-5.0, 5.0, -4.0]
        orientation: 4.71
        
      - position: [0.0, 0.0, -3.0]
        orientation: 0.0
        marker: "loop_close"
        
    transit_speed: 0.4
    enable_loop_closure_detection: true
    revisit_threshold: 2.0  # 米
    
# 任务执行参数
mission_execution:
  default_mission: "default"
  
  # 航点到达条件
  waypoint_tolerance:
    position: 0.5    # 米
    orientation: 0.1 # 弧度
    
  # 超时设置
  waypoint_timeout: 60.0  # 秒
  mission_timeout: 600.0  # 秒
  
  # 错误处理
  on_timeout: "skip"  # skip, retry, abort
  max_retries: 3
  
  # 任务完成行为
  on_completion: "hold"  # hold, return_home, repeat
  
# 安全约束
safety_constraints:
  # 深度限制
  min_depth: -1.0   # 米（最浅）
  max_depth: -30.0  # 米（最深）
  
  # 距离限制
  max_distance_from_origin: 50.0  # 米
  
  # 倾斜限制
  max_pitch: 0.524  # 弧度 (30度)
  max_roll: 0.349  # 弧度 (20度)
  
  # 紧急上浮
  emergency_surface:
    enabled: true
    trigger_depth: -28.0  # 米
    ascent_rate: 0.5     # m/s
    
# 数据记录
data_logging:
  log_waypoints: true
  log_trajectory: true
  log_sensor_data: false  # 大量数据
  
  # 记录格式
  trajectory_format: "csv"  # csv, rosbag
  decimation: 1  # 记录每N个点
